connect:
  image: chamunks/lilypad-connect
  ports:
    - "5091:5091"
  volumes:
    - "./connect/connect.yml:/app/connect.yml"
  ## Restart policies can be set to anything from here https://docs.docker.com/v1.8/reference/run/#restart-policies-restart
  restart: always
